# Generated by Django 2.1.3 on 2018-11-14 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Auditores',
            },
        ),
        migrations.CreateModel(
            name='Efector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cuie', models.CharField(max_length=5)),
                ('activo', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Efectores',
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mae.Auditor')),
                ('efector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mae.Efector')),
            ],
            options={
                'verbose_name_plural': 'Fichas',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero')])),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('activo', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Periodo',
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.AddField(
            model_name='ficha',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mae.Periodo'),
        ),
    ]
